### PR TITLE
Test commit

### PR DESCRIPTION
**Pull request by tomaszrybicki**
Signed-off-by: Tomasz Rybicki <tomasz.rybicki@intel.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-cas/open-cas-telemetry-framework/1)

### CODE REVIEW

**Comment by mariuszbarczak** [comment]
rerun tests

**Comment by mariuszbarczak** [comment]
build

**Comment by tomaszrybicki** [comment]
build

**Comment by tomaszrybicki** [comment]
skip ci

**Comment by tomaszrybicki** [comment]
[skip ci]

**Comment by tomaszrybicki** [comment]
rerun tests

**Comment by tomaszrybicki** [comment]
rerun tests

**Comment by tomaszrybicki** [comment]
rerun tests

**Comment by tomaszrybicki** [comment]
rebuild

**Comment by tomaszrybicki** [comment]
ok to test

**Pull request closed without merging**
